# Generated by Django 4.2.13 on 2024-07-01 15:58

import api.model.challenge
import api.model.submission
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='題目標題', max_length=255)),
                ('description', models.TextField()),
                ('image_url', models.ImageField(default='images/default.png', upload_to=api.model.challenge.upload_to, verbose_name='題目圖片')),
                ('difficulty', models.CharField(choices=[('easy', 'easy'), ('medium', 'medium'), ('hard', 'hard')], default='easy', max_length=255, verbose_name='難度')),
                ('is_valid', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Round',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('is_valid', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('token', models.CharField(max_length=4, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField(default='', verbose_name='程式碼')),
                ('status', models.CharField(choices=[('todo', 'todo'), ('doing', 'doing'), ('fail', 'fail'), ('success', 'success')], default='todo', max_length=255, verbose_name='狀態')),
                ('score', models.IntegerField(default=0, validators=[api.model.submission.Submission.validate_range], verbose_name='分數')),
                ('fitness', models.IntegerField(default=0, validators=[api.model.submission.Submission.validate_range], verbose_name='吻合度')),
                ('word_count', models.IntegerField(default=0, verbose_name='單字數')),
                ('execute_time', models.DurationField(null=True, verbose_name='執行時間')),
                ('stdout', models.TextField(default='', verbose_name='標準輸出')),
                ('stderr', models.TextField(default='', verbose_name='標準錯誤')),
                ('time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='時間')),
                ('draw_image_url', models.TextField(default='', verbose_name='繪圖圖片連結')),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.challenge', verbose_name='挑戰')),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.round', verbose_name='回合')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.team', verbose_name='隊伍')),
            ],
        ),
        migrations.AddField(
            model_name='challenge',
            name='round_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.round'),
        ),
    ]
