# Generated by Django 4.2.11 on 2024-03-28 08:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=256, verbose_name='訂單編號')),
                ('description', models.CharField(max_length=256, verbose_name='訂單描述')),
                ('status', models.CharField(max_length=256, verbose_name='訂單狀態')),
                ('expected_date', models.DateTimeField(verbose_name='預計完成日期')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='操作員工 ID')),
            ],
        ),
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='零件名稱')),
                ('number', models.BigIntegerField(verbose_name='零件數量')),
                ('min_number', models.BigIntegerField(verbose_name='零件最少數量')),
                ('warning', models.BooleanField(verbose_name='警告狀態')),
            ],
        ),
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.BigIntegerField(verbose_name='零件數量')),
                ('order_i', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.order', verbose_name='對應訂單')),
            ],
        ),
    ]
