# Generated by Django 4.2.11 on 2024-04-10 06:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderdetail',
            name='order_i',
        ),
        migrations.AddField(
            model_name='orderdetail',
            name='order_number',
            field=models.CharField(default='XXX-XXX-XXX', max_length=255, verbose_name='對應訂單'),
        ),
        migrations.AddField(
            model_name='orderdetail',
            name='part_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.part', verbose_name='零件 ID'),
        ),
    ]
