# Generated by Django 4.2.11 on 2024-05-12 16:44

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='status',
            field=models.CharField(choices=[('todo', 'todo'), ('doing', 'doing'), ('fail', 'fail'), ('success', 'success')], default='todo', max_length=255, verbose_name='狀態'),
        ),
        migrations.AddField(
            model_name='submission',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='時間'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='challenge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.challenge', verbose_name='挑戰'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='code',
            field=models.TextField(default='', verbose_name='程式碼'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='round',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.round', verbose_name='回合'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='score',
            field=models.IntegerField(default=0, verbose_name='分數'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.team', verbose_name='隊伍'),
        ),
    ]
