# Generated by Django 4.2.11 on 2024-05-13 05:13

import api.model.challenge
import api.model.submission
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_submission_status_submission_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='image_url',
            field=models.ImageField(default='images/default.png', upload_to=api.model.challenge.upload_to, verbose_name='題目圖片'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='score',
            field=models.IntegerField(default=0, validators=[api.model.submission.Submission.validate_range], verbose_name='分數'),
        ),
        migrations.AlterField(
            model_name='team',
            name='token',
            field=models.CharField(max_length=4, unique=True),
        ),
    ]
