# Generated by Django 4.2.11 on 2024-05-15 03:56

import api.model.submission
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_challenge_image_url_alter_submission_score_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='score',
        ),
        migrations.AddField(
            model_name='submission',
            name='fitness',
            field=models.IntegerField(default=0, validators=[api.model.submission.Submission.validate_range], verbose_name='吻合度'),
        ),
        migrations.AddField(
            model_name='submission',
            name='stderr',
            field=models.TextField(default='', verbose_name='標準錯誤'),
        ),
        migrations.AddField(
            model_name='submission',
            name='stdout',
            field=models.TextField(default='', verbose_name='標準輸出'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 15, 3, 56, 44, 142947, tzinfo=datetime.timezone.utc), verbose_name='時間'),
        ),
    ]
