# Generated by Django 4.2.11 on 2024-05-16 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_submission_execute_time_submission_line_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='round',
            name='end_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='round',
            name='start_time',
            field=models.TimeField(),
        ),
    ]
