# Generated by Django 4.2.13 on 2024-05-19 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_submission_line_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='submission',
            old_name='line_number',
            new_name='word_count',
        ),
    ]
