# Generated by Django 4.2.13 on 2024-05-19 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_rename_line_number_submission_word_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='title',
            field=models.CharField(default='題目標題', max_length=255),
        ),
    ]
