# Generated by Django 4.2.13 on 2024-05-19 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_challenge_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='round',
            name='end_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='round',
            name='start_time',
            field=models.DateTimeField(),
        ),
    ]
