# Generated by Django 4.2.13 on 2024-05-20 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_round_end_time_alter_round_start_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='difficulty',
            field=models.CharField(choices=[('easy', 'easy'), ('normal', 'normal'), ('hard', 'hard')], default='easy', max_length=255, verbose_name='難度'),
        ),
    ]
