# Generated by Django 4.2.13 on 2024-06-30 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_challenge_difficulty'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='draw_image_url',
            field=models.TextField(default='', verbose_name='繪圖圖片連結'),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='difficulty',
            field=models.CharField(choices=[('easy', 'easy'), ('medium', 'medium'), ('hard', 'hard')], default='easy', max_length=255, verbose_name='難度'),
        ),
    ]
